### ISSUE TITLE
Question: Relation to tf/contrib/crf

### ISSUE THREAD

**Issue by Rikorose** [sadeepj/crfasrnn_keras#12]
Hi,

Thanks for sharing this code. How does this implementation differ from the [crf code](https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/contrib/crf/python/ops/crf.py) in the tensorflow repo? Can a higher order MRF (semi-MRF) be modeled?

**Comment by sadeepj** [comment]
@Rikorose I'm not familiar with the Tensorflow CRF code you pointed to. But it looks like a more generic CRF implementation.

Our implementation is specific to dense CRFs defined on 2D images with Gaussian edge potentials. Please see http://www.robots.ox.ac.uk/~szheng/papers/CRFasRNN.pdf for details. We have done some follow up work on higher order CRFs as well (see https://arxiv.org/abs/1511.08119). But the source codes for those works are not publicly available.
