### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by XhqGlorry11** [sadeepj/crfasrnn_keras#17]
@sadeepj Hi, thx at first. I wonder is it possible to train a CRF-RNN model using the compiled "high_dim_filter.so" in Tensorflow/Keras environment? I mean is backprop part also included in "high_dim_filter.so"?Thx.

**Comment by sadeepj** [comment]
@XhqGlorry11 Yes, it is included. More specifically, it has been implemented here: https://github.com/sadeepj/crfasrnn_keras/blob/master/high_dim_filter_grad.py

**Comment by XhqGlorry11** [comment]
@sadeepj Got that and thx again！

**Comment by cv-shiyanshi** [comment]
@XhqGlorry11  Hi, have you completed this training code? I will be greatly appreciated if you give me some advice. My email is 1587478816@qq.com .Thanks!
