### ISSUE TITLE
nsync_cv.h  No such a file or directory

### ISSUE THREAD

**Issue by zxxdls** [sadeepj/crfasrnn_keras#19]
I use anaconda with python 2.7  tensorflow 1.4 and when I compile  the file compile.sh there is an error about

In file included from /home/zxxdls/.local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/platform/mutex.h:31:0,
                 from /home/zxxdls/.local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/op.h:32,
                 from high_dim_filter.cc:25:
/home/zxxdls/.local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/platform/default/mutex.h:25:22: fatal error: nsync_cv.h: No such a file or directory
compilation terminated.
In file included from /home/zxxdls/.local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/platform/mutex.h:31:0,
                 from /home/zxxdls/.local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/variant.h:31,
                 from /home/zxxdls/.local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/allocator.h:26,
                 from /home/zxxdls/.local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/framework/tensor.h:20,
                 from modified_permutohedral.h:42,
                 from modified_permutohedral.cc:33:
/home/zxxdls/.local/lib/python2.7/site-packages/tensorflow/include/tensorflow/core/platform/default/mutex.h:25:22: fatal error: nsync_cv.h: No such a file or directory
It seems that there is an error about building a custom op in tf 1.4
I want to know how to solve it or I want to know what is the corresponding version of tf in this project
Thanks very much

**Comment by DavidNorman** [comment]
I have the same issue.  Building on OS/X without CUDA.

**Comment by DavidNorman** [comment]
maybe see https://github.com/kaldi-asr/kaldi/issues/1898

**Comment by DavidNorman** [comment]
The following dependency `"@nsync//:nsync_headers"` is in `framework_lite` but not in `framework`, or in `framework_internal`.    I suspect this is an error caused when the lite framework came online.

**Comment by ZHmao** [comment]
add `nsync_cv.h` include：`-I$TF_INC/external/nsync/public`

maybe help you
I found it from https://www.tensorflow.org/extend/adding_an_op#build_the_op_library

below is official demo
```
TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')
g++ -std=c++11 -shared zero_out.cc -o zero_out.so -fPIC -I$TF_INC -I$TF_INC/external/nsync/public -L$TF_LIB -ltensorflow_framework -O2
```

**Comment by sadeepj** [comment]
@zxxdls @DavidNorman @ZHmao Thanks all for reporting this bug and suggesting the fix. This has now been fixed on the master branch. Please let us know if you have further issues using the code.
