### ISSUE TITLE
compile file

### ISSUE THREAD

**Issue by jeansely** [sadeepj/crfasrnn_keras#2]
Hello,
in windows os , how compile file?
Thanks.

**Comment by sadeepj** [comment]
@jeansely, I haven't tested this on Windows. You'd have to resort to generic Tensorflow custom op building guides to get help. Unfortunately, the [Tensorflow's official guide of adding a custom op](https://www.tensorflow.org/extend/adding_an_op) doesn't (yet) include instructions for building on Windows. But the following links might be helpful:

https://github.com/tensorflow/models/issues/1103
https://github.com/tensorflow/models/issues/1103#issuecomment-290155681
https://github.com/tensorflow/models/issues/1103#issuecomment-302945787

**Comment by sadeepj** [comment]
Updated the README in b990ae92285141aff1a04436b46ca819599414d9.

**Comment by laitaihu** [comment]
Hello, did you sloved the problem about run this code on Windows?
