### ISSUE TITLE
3D images and batch size greater than 1

### ISSUE THREAD

**Issue by MiguelMonteiro** [sadeepj/crfasrnn_keras#20]
As far as I can tell this code only works for 2D images. 
Would expanding this code to work with 3D images (possibly N-D) require changing the C++ code or is it just a matter of rewriting some of the python and tensorflow code?
In addition is the batch size limitation a property of the systems' design or can it fixed?

Keep up the good work!

**Comment by sadeepj** [comment]
@MiguelMonteiro Extending this to 3D and N-D images would require significant re-engineering. I don't think even the FCN part of the network will work out-of-the-box on 3D images. Our formulation of CRF-RNN (http://www.robots.ox.ac.uk/~szheng/papers/CRFasRNN.pdf) is specific to 2D images, but can be extended to 3D. This will need some thinking and then modifying the C++ code.

However, the batch size limitation (for 2D images) can be fixed relatively easily. It can even be done by changing only the Python code in https://github.com/sadeepj/crfasrnn_keras/blob/master/crfrnn_layer.py. But doing it in C++ would be more efficient. I'm planning to do this and resolve #6 sometime soon.

**Comment by pvthuy** [comment]
Did anyone fix this?
