### ISSUE TITLE
about crfrnn_layer three weights

### ISSUE THREAD

**Issue by alexliyang** [sadeepj/crfasrnn_keras#22]
Excuse me, I have a question : when training, crfrnn_layer's three weights are trained or not?

**Comment by sadeepj** [comment]
Hi @alexliyang, They are trained as well. CrfRnnLayer in this implementation supports back-propagation.

**Comment by runzeer** [comment]
thx for your excellent work! Now I have a tensorflow framework.So can I use the crfrnnlayer as a layer behind the layers from tensorflow such as slim?
