### ISSUE TITLE
Is there something wrong with q_values' computation ? 

### ISSUE THREAD

**Issue by LandyGuo** [sadeepj/crfasrnn_keras#23]
According to the original paper, 

> we use Ui(l) to denote the **negative** of the unary energy intoduced in the previous section

since unary energy is computed as: -log(p) , where p = softmax(FCN_OUT), so the initial q_values in crfrnn_layer.py should be  log(softmax(unaries))  instead of  directly using unaries ?  Am I right ? hoping for your response.

**Comment by glhfgg1024** [comment]
Hi, please check this issue: 
https://github.com/sadeepj/crfasrnn_keras/issues/4
