### ISSUE TITLE
can't download the model weights

### ISSUE THREAD

**Issue by lihuihui666** [sadeepj/crfasrnn_keras#26]
Hello and I really appreciate your work, but there is a problem. I clicked the "here"button wishing to download the model weights, but it didn't work, could you please solve this?

**Comment by sadeepj** [comment]
Hi @lihuihui666 

I've just tested the link https://goo.gl/ciEYZi. It still works for me. Can you try again?

**Comment by sadeepj** [comment]
@lihuihui666 Alternatively, you can now download it from https://github.com/sadeepj/crfasrnn_keras/releases/download/v1.0/crfrnn_keras_model.h5

**Comment by lihuihui666** [comment]
thanks a lot! I managed to download it
