### ISSUE TITLE
What is the simplest way of using the label on original image?

### ISSUE THREAD

**Issue by leyuan** [sadeepj/crfasrnn_keras#28]
Hi,

It's a really beginner question. I can use `for` loop to loop for each pixel in the `label_image` but I feel there should be a better way to apply the label on top of the input image?

Looking at this [alpha_composite method](https://pillow.readthedocs.io/en/stable/reference/Image.html#image-processing), if someone knows a neat way please let me know!

Thank you.

**Comment by leyuan** [comment]
What I got so far...

```
# Load Original Image and Segmentation
# Convert them to np.array
im = Image.open(input_file)
im = np.array(im)
seg = np.array(segmentation)

# apply mask
rows = seg.shape[0]
cols = seg.shape[1]
print("rows #:", rows)
print("cols #:", cols)

for x in range(0, rows):
    for y in range(0, cols):
        if seg[x][y] == 0:
            im[x][y] = np.array([255, 255, 255], dtype='uint8')

Image.fromarray(im).show()
```

**Comment by Toz3wm** [comment]
Hi @leyuan, I think this question is out of scope of github, let alone of this repo :-) 
You better ask such questions on stackoverflow, or read the numpy documentation !

(short answer : juste do 
``` im[seg == 0] = np.array([255,  255, 255],  dtype='uint8') ```
