### ISSUE TITLE
about training code

### ISSUE THREAD

**Issue by amiltonwong** [sadeepj/crfasrnn_keras#3]
Hi, @sadeepj ,

Thanks for releasing TF/Keras version for crfasrnn. However it seems the training code for the model is not provided, when will it be released?

Thanks!

**Comment by sadeepj** [comment]
@amiltonwong We originally trained this with Caffe. However, given the model definition provided with this code, it should be easy to train new models using the standard Keras API (see https://keras.io/getting-started/sequential-model-guide/#training for example).
All the training parameters are found in the paper: http://www.robots.ox.ac.uk/~szheng/papers/CRFasRNN.pdf.
I'll try to release Keras training code as well in the future. If someone else does it before me, a pull request would be greatly appreciated.

**Comment by AndrewDixHill** [comment]
Hi sadeepj
I'd like to second that "thank you" for making a crf for python/keras.
I am trying to train a model so I can import my own weights but I am not entirely sure of the architecture used to build the  crfrnn_keras_model.h5

Should I use the entire structure of the crfrnn_model.py? or just up to the Deconvolution?

**Comment by XhqGlorry11** [comment]
@sadeepj Hi sadeepj, thx at first. It seems that there are 3 trainable parameters of CRF-RNN: compatibility _matrix, spatial_ker_weights and bilateral_ker_weighs. And I want to know how does theta_alpha, theta_beta and theta_gamma is confirmed? Could you give me some tips? ^ ^

**Comment by sadeepj** [comment]
@XhqGlorry11 

You're correct - those are the three trainable parameters in CRF-RNN. The theta_alpha, theta_beta, and theta_gamma values can be decided by cross validation. But you don't have to work hard to optimize those hyperparameters. You'll be fine as long as they are in the correct order.

**Comment by manishh** [comment]
> @amiltonwong We originally trained this with Caffe. However, given the model definition provided with this code, it should be easy to train new models using the standard Keras API (see https://keras.io/getting-started/sequential-model-guide/#training for example).
> All the training parameters are found in the paper: [http://www.robots.ox.ac.uk/~szheng/papers/CRFasRNN.pdf](http://www.robots.ox.ac.uk/%7Eszheng/papers/CRFasRNN.pdf).
> I'll try to release Keras training code as well in the future. If someone else does it before me, a pull request would be greatly appreciated.

Do you have this training code available now?

**Comment by gyheart** [comment]
> o you have this training code available now?

I also want to know is the training code  avaiable now?
