### ISSUE TITLE
Alternative repository

### ISSUE THREAD

**Issue by MiguelMonteiro** [sadeepj/crfasrnn_keras#34]
Just wanted to let you know that I developed an alternative repo which is more flexible in the shape and number of channels of the images (any 2D, 3D multi-channel image should work) and that has both a CPU and GPU kernel.
Please check the link if you are interested in more info.
[https://github.com/MiguelMonteiro/CRFasRNNLayer](https://github.com/MiguelMonteiro/CRFasRNNLayer)

**Comment by iperov** [comment]
so is there no way to port permutohedral_lattice to native tensorflow ?

**Comment by glhfgg1024** [comment]
Hi @MiguelMonteiro , great work! Thanks a lot for your sharing!

**Comment by MiguelMonteiro** [comment]
@glhfgg1024 Btw I did try this for 3D medical imaging segmentation and couldn't get a statistically significant performance increase. Let me know if you observe something different.

**Comment by glhfgg1024** [comment]
@MiguelMonteiro , yes, in my case, the improvement on dice was also limited (1%~2%), and my MICCAI submission has been rejected. I agree with you that the expert contours in medical images have less defined edges as those in natural images. For example, for lung CT tumor segmentation, the expert contours include many voxels with -100~-800 HU values. And when using the CRF, the module still cannot correct the mis-classified voxels and may even lead to worse segmentation.

**Comment by iperov** [comment]
can permutohedral_lattice be replaced by something implemented by native tf ?

**Comment by MiguelMonteiro** [comment]
Well it's just a bilateral filter or a gaussian filter. I am sure you could implement a brute force implementation in native tensorflow if you really wanted to. However, I think it is best to keep questions regarding this topic on the permutohedral_lattice 's page.
