### ISSUE TITLE
Is there any possibility to run on windows?

### ISSUE THREAD

**Issue by extra159** [sadeepj/crfasrnn_keras#39]
Hello,
I have installed anaconda on windows. So, can you tell me that is there any possibility to run it with anaconda on windows?

**Comment by manojgali** [comment]
any response is appreciated, i need the crf for project work

**Comment by sadeepj** [comment]
The Tensorflow/Keras code only supports Linux and Mac due to the complications of compiling Tensorflow custom ops. But there's a PyTorch implementation of this work now https://github.com/sadeepj/crfasrnn_pytorch, which you might be able to run on Windows.
