### ISSUE TITLE
The result of the test_gradients.py？

### ISSUE THREAD

**Issue by gyheart** [sadeepj/crfasrnn_keras#52]
Hi，
Can you tell me the result of the test_gradients.py? I run the test_gradients.py, I want to know if it work well in my environment.

Thanks.

**Comment by sadeepj** [comment]
As the name implies, this script tests the gradient calculation of the CRF-RNN layer. A typical output is shown below:

`
crfasrnn_keras/src$ python test_gradients.py
<Tensorflow initialisation log messages>
Gradient check: measure1 = 0.000089, measure2 = 0.009579
Gradient check: success!
..
----------------------------------------------------------------------
Ran 2 tests in 1.887s

OK

`
