### ISSUE TITLE
undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by fuweilin92** [sadeepj/crfasrnn_keras#53]
The last step, run_demo.py, I get this error:

Traceback (most recent call last):
  File "run_demo.py", line 27, in <module>
    from crfrnn_model import get_crfrnn_model_def
  File "./src/crfrnn_model.py", line 28, in <module>
    from crfrnn_layer import CrfRnnLayer
  File "./src/crfrnn_layer.py", line 28, in <module>
    import high_dim_filter_loader
  File "./src/high_dim_filter_loader.py", line 28, in <module>
    custom_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'cpp', 'high_dim_filter.so'))
  File "/home/fu/.local/share/virtualenvs/my_pipenv-ITNpTMim/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./src/cpp/high_dim_filter.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

What can we do?

**Comment by xingtianxia1314** [comment]
I have the same problem with you.but I don't kown how to correct it.
Mine is tensorflow0gpu-1.12,cuda-9.0,cudnn7.0.

**Comment by DangDinhQuocTrung** [comment]
I have the same problem with tensorflow-gpu 1.12 and keras 2.2.4, any solution?

**Comment by Golbstein** [comment]
I've the same problem

**Comment by mjoppich** [comment]
I guess the following should compile the library just fine ... remember to adapt pathes for your cases ;)

`g++ -std=c++11 -shared high_dim_filter.cc modified_permutohedral.cc -o high_dim_filter.so -fPIC -I /usr/local/lib/python2.7/dist-packages/tensorflow/include -O2 -D_GLIBCXX_USE_CXX11_ABI=0 -I ~/.local/lib/python2.7/site-packages/tensorflow/include/external/nsync/public -L/usr/local/lib/python2.7/dist-packages/tensorflow -ltensorflow_framework`

**Comment by panfengli** [comment]
```
TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )

g++ -std=c++11 -shared high_dim_filter.cc modified_permutohedral.cc -o high_dim_filter.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2
```

**Comment by qchenclaire** [comment]
> @panfengli
> Could you tell me that where should I fixed using the follow code？Thank you!
> 
> TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
> TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
> 
> g++ -std=c++11 -shared high_dim_filter.cc modified_permutohedral.cc -o high_dim_filter.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2

These can be run as terminal commands. I'm using tensorflow 1.10 and these commands removed the error for me

**Comment by cv-shiyanshi** [comment]
@qchenclaire Thank you so much,I solved it by your recommend. 
By the way,Could you tell me that where can I find the training of CRF-RNN used tensorflow?

**Comment by zhilongjiang** [comment]
I have the exactly same problem. 

tensorflow-gpu 1.120
cuda V10.0.130
cudnn 7.3

**Comment by JadBatmobile** [comment]
@panfengli, your instructions apply only to the CPU implementation. I am getting this error on the GPU support branch as well.

**Comment by JadBatmobile** [comment]
It turned out i actually had to modify:

`
# Set some more flags if the Tensorflow version is >= 1.4
ifeq ($(TF_VERSION_GTE_1_4), 1)
CFLAGS += -I$(TF_INC)/external/nsync/public
LDFLAGS := -L$(TF_LIB) -ltensorflow_framework -L/usr/local/cuda/lib64 -lcuda -lcudart
else
	LDFLAGS :=
endif
`

To:
`CFLAGS += -I$(TF_INC)/external/nsync/public
LDFLAGS := -L$(TF_LIB) -ltensorflow_framework -L/usr/local/cuda/lib64 -lcuda -lcudart`

**Comment by JadBatmobile** [comment]
it seemed like the conditional was not doing what it was supposed to be doing.. perhaps the parsing is wrong.. i really suck and writing MakeFiles

**Comment by skq-5233** [comment]
Hello! When I run the sh.compile.sh command, it compiles successfully, but when I run train.py, I get an error: undefined symbol:_ZTIN10tensorflow8opkernelE. I checked a lot of information on the Internet and did not solve it. Hope you help me see what is the problem. Thanks again! ! !
ubuntu :16.04 ; nvidia-driver-440;cuda:10.0; cudnn:7.5.0; tensorflow-gpu:1.13.1; gcc/g++:5.4.0;
![image](https://user-images.githubusercontent.com/65205043/84976284-13779b00-b15a-11ea-87ff-9a07861aa1c2.png)

@qchenclaire @zhilongjiang

**Comment by skq-5233** [comment]
> The last step, run_demo.py, I get this error:
> 
> Traceback (most recent call last):
> File "run_demo.py", line 27, in
> from crfrnn_model import get_crfrnn_model_def
> File "./src/crfrnn_model.py", line 28, in
> from crfrnn_layer import CrfRnnLayer
> File "./src/crfrnn_layer.py", line 28, in
> import high_dim_filter_loader
> File "./src/high_dim_filter_loader.py", line 28, in
> custom_module = tf.load_op_library(os.path.join(os.path.dirname(**file**), 'cpp', 'high_dim_filter.so'))
> File "/home/fu/.local/share/virtualenvs/my_pipenv-ITNpTMim/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
> lib_handle = py_tf.TF_LoadLibrary(library_filename)
> tensorflow.python.framework.errors_impl.NotFoundError: ./src/cpp/high_dim_filter.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
> 
> What can we do?
Hello, may I ask how this problem was finally solved?Thank you very much!

**Comment by skq-5233** [comment]
> > @panfengli
> > Could you tell me that where should I fixed using the follow code？Thank you!
> > TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
> > TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
> > g++ -std=c++11 -shared high_dim_filter.cc modified_permutohedral.cc -o high_dim_filter.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2
> 
> These can be run as terminal commands. I'm using tensorflow 1.10 and these commands removed the error for me



> > @panfengli
> > Could you tell me that where should I fixed using the follow code？Thank you!
> > TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
> > TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
> > g++ -std=c++11 -shared high_dim_filter.cc modified_permutohedral.cc -o high_dim_filter.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2
> 
> These can be run as terminal commands. I'm using tensorflow 1.10 and these commands removed the error for me

Hello, may I ask how this problem was finally solved?Thank you very much!

**Comment by skq-5233** [comment]
> I have the same problem with you.but I don't kown how to correct it.
> Mine is tensorflow0gpu-1.12,cuda-9.0,cudnn7.0.

Hello! How did you finally solve the problem.Thanks a lot!!

**Comment by skq-5233** [comment]
> > @panfengli
> > Could you tell me that where should I fixed using the follow code？Thank you!
> > TF_CFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_compile_flags()))') )
> > TF_LFLAGS=( $(python -c 'import tensorflow as tf; print(" ".join(tf.sysconfig.get_link_flags()))') )
> > g++ -std=c++11 -shared high_dim_filter.cc modified_permutohedral.cc -o high_dim_filter.so -fPIC ${TF_CFLAGS[@]} ${TF_LFLAGS[@]} -O2
> 
> These can be run as terminal commands. I'm using tensorflow 1.10 and these commands removed the error for me

Hello! How did you finally solve the problem.Thanks a lot!!
