### ISSUE TITLE
Compared to pydensecrf, crfasrnn seems do not have two `compat` parameters.

### ISSUE THREAD

**Issue by panfengli** [sadeepj/crfasrnn_keras#54]
For example,

```
d.addPairwiseGaussian(sxy=3, compat=3)
d.addPairwiseBilateral(sxy=80, srgb=13, rgbim=im, compat=10)
```

Here `theta_alpha` is 80, `theta_beta` is 13 and `theta_gamma` is 3 which corresponds to the 3 parameters in crfrnn network. However, the two `compat` parameters seems not available in crfrnn model.

**Comment by sadeepj** [comment]
Hi @panfengli these parameters in pydensecrf seems to be related to the compatibility matrices and kernel weights. See Section 4.4 of https://www.robots.ox.ac.uk/~szheng/papers/CRFasRNN.pdf for more details. 

In https://github.com/sadeepj/crfasrnn_keras/blob/master/src/crfrnn_layer.py#L40, _self.spatial_ker_weights_, _self.bilateral_ker_weights_ and _self.compatibility_matrix_ combined have the same effect as these parameters. All of these are automatically learned using backpropagation during the training of CRF-RNN (please see the above paper for more details).
