### ISSUE TITLE
Do we have pure tensorflow version?

### ISSUE THREAD

**Issue by zxpeter** [sadeepj/crfasrnn_keras#64]
Hi,
Do we have pure tensorflow version or we just have keras+tensorflow version?

Thanks.

**Comment by sadeepj** [comment]
At the moment I've only released a keras+tensorflow version. But I don't think it's too difficult to write your own Tensorflow version by converting the logic in https://github.com/sadeepj/crfasrnn_keras/blob/master/src/crfrnn_layer.py to pure Tensorflow.
