### ISSUE TITLE
high_dim_filter.so NotFoundError

### ISSUE THREAD

**Issue by daifeng2016** [sadeepj/crfasrnn_keras#65]
Hi, I have created the "high_dim_filter.so" in  the file using step 4. However, there still exist errors like "tensorflow.python.framework.errors_impl.NotFoundError: E:/TEST/DownLoadPrj/CRF/crfasrnn_keras-master/crfasrnn_keras-master/src/cpp/high_dim_filter.so: cannot open shared object file: No such file or directory" . What is the problem?

**Comment by sadeepj** [comment]
@daifeng2016 Are you using Windows OS? As discussed in https://github.com/sadeepj/crfasrnn_keras/issues/13 we don't officially support Windows yet.

**Comment by skq-5233** [comment]
Hello! When I run the sh.compile.sh command, it compiles successfully, but when I run train.py, I get an error: undefined symbol:_ZTIN10tensorflow8opkernelE. I checked a lot of information on the Internet and did not solve it. Hope you help me see what is the problem. Thanks again! ! !
ubuntu :16.04 ; nvidia-driver-440;cuda:10.0; cudnn:7.5.0; tensorflow-gpu:1.13.1; gcc/g++:5.4.0;
![image](https://user-images.githubusercontent.com/65205043/84975740-c7782680-b158-11ea-93c0-13502e4f7f39.png)
 
@sadeepj
