### ISSUE TITLE
can not make

### ISSUE THREAD

**Issue by jovahe** [sadeepj/crfasrnn_keras#67]
when I execute the command of "make" in the directory "crfasrnn_keras/src/cpp"
I got the following error:
make: python: Command not found
make: python: Command not found
/bin/sh: 1: python: not found
expr: missing operand
Try 'expr --help' for more information.
/bin/sh: 1: [: -gt: unexpected operator
g++ -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -shared -fPIC -I -O2  -o high_dim_filter.so high_dim_filter.cc modified_permutohedral.cc 
high_dim_filter.cc:25:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
compilation terminated.
In file included from modified_permutohedral.cc:33:0:
modified_permutohedral.h:42:46: fatal error: tensorflow/core/framework/tensor.h: No such file or directory
compilation terminated.
Makefile:49: recipe for target 'high_dim_filter.so' failed
make: *** [high_dim_filter.so] Error 1

can you help me to figure out this problem?

**Comment by sadeepj** [comment]
@jovahe, looking at the error message:

> make: python: Command not found
> make: python: Command not found,

it looks like you don't have "python" in your executable PATH.

**Comment by jovahe** [comment]
@sadeepj ,thanks a lot.According to your prompt, I figure out this problem by modifying Makefile as following:
PYTHON=python3
