### ISSUE TITLE
demo run failed

### ISSUE THREAD

**Issue by hassanrazakhalid** [sadeepj/crfasrnn_keras#69]
After i run demo i get error. How to fix this
Tensrflow version : 1.14.0 (CPU version)
Ubuntu: 18.04

```
Traceback (most recent call last):
  File "run_demo.py", line 27, in <module>
    from crfrnn_model import get_crfrnn_model_def
  File "./src/crfrnn_model.py", line 28, in <module>
    from crfrnn_layer import CrfRnnLayer
  File "./src/crfrnn_layer.py", line 28, in <module>
    import high_dim_filter_loader
  File "./src/high_dim_filter_loader.py", line 28, in <module>
    custom_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'cpp', 'high_dim_filter.so'))
  File "/home/hassan/miniconda3/envs/crfasrnn/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./src/cpp/high_dim_filter.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
```

**Comment by zhangbaijin** [comment]
sorry，i have the same problem，can you tell how should i solve it？thanks！

**Comment by skq-5233** [comment]
> sorry，i have the same problem，can you tell how should i solve it？thanks！

Hello! How did you finally solve the problem.Thanks a lot!!

**Comment by skq-5233** [comment]
> After i run demo i get error. How to fix this
> Tensrflow version : 1.14.0 (CPU version)
> Ubuntu: 18.04
> 
> ```
> Traceback (most recent call last):
>   File "run_demo.py", line 27, in <module>
>     from crfrnn_model import get_crfrnn_model_def
>   File "./src/crfrnn_model.py", line 28, in <module>
>     from crfrnn_layer import CrfRnnLayer
>   File "./src/crfrnn_layer.py", line 28, in <module>
>     import high_dim_filter_loader
>   File "./src/high_dim_filter_loader.py", line 28, in <module>
>     custom_module = tf.load_op_library(os.path.join(os.path.dirname(__file__), 'cpp', 'high_dim_filter.so'))
>   File "/home/hassan/miniconda3/envs/crfasrnn/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
>     lib_handle = py_tf.TF_LoadLibrary(library_filename)
> tensorflow.python.framework.errors_impl.NotFoundError: ./src/cpp/high_dim_filter.so: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
> ```
Hello! How did you finally solve the problem.Thanks a lot!!

**Comment by Hui-Yao** [comment]
> sorry，i have the same problem，can you tell how should i solve it？thanks！

TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')

g++ -std=c++11 -D_GLIBCXX_USE_CXX11_ABI=0 -shared high_dim_filter.cc modified_permutohedral.cc -o high_dim_filter.so -fPIC -I $TF_INC -I$TF_INC/external/nsync/public/ -L$TF_LIB -ltensorflow_framework -O2
There is no problem in compiling, but when I run the train.py code, I will get an error.
undefined symbol: _ZTIN10tensorflow8OpKernelE @ sadeepj @hassanrazakhalid @sirotenko @Kautenja Thanks a lot!!!
