### ISSUE TITLE
Submitting operation to Tensorflow

### ISSUE THREAD

**Issue by fferroni** [sadeepj/crfasrnn_keras#7]
Hi!

Great work! More of a comment than an issue. Are you planning on submitting the operations for the CRFs to Tensorflow contrib? There is already a tensorflow.contrib.crf so perhaps this could go there?

Given CRFs are common in segmentation, I doubt you would have troubles convincing them to add the functionality.

**Comment by sadeepj** [comment]
Thanks for the suggestion! I'm planning to completed the GPU version of high_dim_filter op sometime soon. Once that's done I'll consider making everything more polished and submitting to Tensorflow contrib.
